#!/bin/bash
set -euo pipefail

# Brief Signal — Weekly briefing generation pipeline
# Runs Sunday evening; generates briefing for the following Monday.
# Stages 1-2 are fault-tolerant; Stage 3 failure is fatal (no PR created).

LOG_DIR="$(dirname "$0")/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="${LOG_DIR}/generate-$(date +%Y-%m-%d).log"

log() { echo "[$(date '+%H:%M:%S')] $*" | tee -a "$LOG_FILE"; }

# Monday's date (Sunday + 1 day)
MONDAY_DATE=$(date -v+1d +%Y-%m-%d)
BRANCH="briefing/${MONDAY_DATE}"
PLAYLIST_URL="https://www.youtube.com/playlist?list=PL1FeClOi-gXpoHHLPfOgeGltGMNWY9Wjk"

REPO="siguy/brief-signal"
INFO_AGG_DIR="$HOME/info-agg"
BRIEF_SIGNAL_DIR="$HOME/brief-signal"

log "=== Brief Signal Weekly Generation ==="
log "Target date: ${MONDAY_DATE}"
log "Branch: ${BRANCH}"

# Guard: skip if PR already exists for this week
EXISTING_PR=$(gh pr list --repo "$REPO" --head "$BRANCH" --json number --jq '.[0].number' 2>/dev/null || true)
if [ -n "$EXISTING_PR" ]; then
  log "PR #${EXISTING_PR} already exists for ${BRANCH}. Skipping."
  exit 0
fi

# ---------------------------------------------------------------------------
# Stage 1: Extract X bookmarks (~15-30 min)
# ---------------------------------------------------------------------------
log "--- Stage 1: Extracting X bookmarks ---"
cd "$INFO_AGG_DIR"
if claude -p --dangerously-skip-permissions "Run /extract-bookmarks" >> "$LOG_FILE" 2>&1; then
  log "Stage 1 complete: bookmarks extracted."
else
  log "WARN: Stage 1 failed (bookmark extraction). Continuing..."
fi

# ---------------------------------------------------------------------------
# Stage 2: Extract YouTube playlist (~5-15 min)
# ---------------------------------------------------------------------------
log "--- Stage 2: Extracting YouTube playlist ---"
cd "$INFO_AGG_DIR"
if claude -p --dangerously-skip-permissions "Run /extract-playlist $PLAYLIST_URL" >> "$LOG_FILE" 2>&1; then
  log "Stage 2 complete: playlist extracted."
else
  log "WARN: Stage 2 failed (playlist extraction). Continuing..."
fi

# ---------------------------------------------------------------------------
# Stage 3: Generate briefing (~5-10 min)
# ---------------------------------------------------------------------------
log "--- Stage 3: Generating briefing ---"
cd "$BRIEF_SIGNAL_DIR"
git checkout main
git pull origin main
git checkout -b "$BRANCH"

if claude -p --dangerously-skip-permissions "Run /generate-briefing" >> "$LOG_FILE" 2>&1; then
  log "Stage 3 complete: briefing generated."
else
  log "ERROR: Stage 3 failed (briefing generation). Cleaning up."
  git checkout main
  git branch -D "$BRANCH"
  exit 1
fi

# ---------------------------------------------------------------------------
# Stage 4: Fetch OG images, commit, push, open PR
# ---------------------------------------------------------------------------
log "--- Stage 4: Committing and opening PR ---"
npm run fetch-images >> "$LOG_FILE" 2>&1 || log "WARN: Some OG images failed to fetch."

git add content/briefings/
git commit -m "Add briefing: ${MONDAY_DATE}"
git push -u origin "$BRANCH"

PR_BODY="$(cat <<PREOF
## Weekly AI Market Briefing — ${MONDAY_DATE}

Auto-generated by the Brief Signal pipeline.

### Review checklist
- [ ] Read through briefing for accuracy
- [ ] Check source links work
- [ ] Verify OG images loaded
- [ ] Edit any wording/tone issues

### Pipeline stages
- **Bookmarks:** Check log for warnings
- **Playlist:** Check log for warnings
- **Briefing:** Generated successfully

Merge to deploy to GitHub Pages.
PREOF
)"

gh pr create \
  --repo "$REPO" \
  --title "Briefing: Week of ${MONDAY_DATE}" \
  --body "$PR_BODY"

log "PR created. Returning to main."
git checkout main
log "=== Done ==="
