#!/bin/bash
set -euo pipefail

# Brief Signal — Weekly briefing generation pipeline
# Runs Sunday evening; generates briefing for the following Monday.
# Extractions (Stages 1-3) run in parallel and are fault-tolerant.
# Stage 4 (briefing generation) failure is fatal (no PR created).
#
# After merging the briefing PR, run audio separately:
#   npm run audio:pr    → generates audio script + opens PR for review
#   npm run audio:generate → generates MP3 from reviewed script
# Subscriber email is sent when the audio PR is merged (triggers on new .mp3).

LOG_DIR="$(dirname "$0")/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="${LOG_DIR}/generate-$(date +%Y-%m-%d).log"

log() { echo "[$(date '+%H:%M:%S')] $*" | tee -a "$LOG_FILE"; }

# Monday's date (Sunday + 1 day)
MONDAY_DATE=$(date -v+1d +%Y-%m-%d)
BRANCH="briefing/${MONDAY_DATE}"
PLAYLIST_URL="https://www.youtube.com/playlist?list=PL1FeClOi-gXpoHHLPfOgeGltGMNWY9Wjk"

REPO="siguy/brief-signal"
INFO_AGG_DIR="$HOME/info-agg"
BRIEF_SIGNAL_DIR="$HOME/brief-signal"

log "=== Brief Signal Weekly Generation ==="
log "Target date: ${MONDAY_DATE}"
log "Branch: ${BRANCH}"

# Guard: skip if PR already exists for this week
EXISTING_PR=$(gh pr list --repo "$REPO" --head "$BRANCH" --json number --jq '.[0].number' 2>/dev/null || true)
if [ -n "$EXISTING_PR" ]; then
  log "PR #${EXISTING_PR} already exists for ${BRANCH}. Skipping."
  exit 0
fi

# ---------------------------------------------------------------------------
# Stages 1-3: Extract all sources in parallel (~30-45 min total)
# Each extraction is independent and fault-tolerant.
# ---------------------------------------------------------------------------
log "--- Starting parallel extractions ---"

# Stage 1: Extract X bookmarks (background)
(
  log "Stage 1: Extracting X bookmarks..."
  cd "$INFO_AGG_DIR"
  if claude -p --dangerously-skip-permissions "Run /extract-bookmarks" >> "$LOG_FILE" 2>&1; then
    log "Stage 1 complete: bookmarks extracted."
  else
    log "WARN: Stage 1 failed (bookmark extraction). Continuing..."
  fi
) &
PID_BOOKMARKS=$!

# Stage 2: Extract YouTube playlist (background)
(
  log "Stage 2: Extracting YouTube playlist..."
  cd "$INFO_AGG_DIR"
  if claude -p --dangerously-skip-permissions "Run /extract-playlist $PLAYLIST_URL" >> "$LOG_FILE" 2>&1; then
    log "Stage 2 complete: playlist extracted."
  else
    log "WARN: Stage 2 failed (playlist extraction). Continuing..."
  fi
) &
PID_PLAYLIST=$!

# Stage 3: Extract podcasts (background)
(
  log "Stage 3: Extracting podcasts..."
  cd "$BRIEF_SIGNAL_DIR"
  if node scripts/extract-podcasts.js >> "$LOG_FILE" 2>&1; then
    log "Stage 3 complete: podcasts extracted."
  else
    log "WARN: Stage 3 failed (podcast extraction). Continuing..."
  fi
) &
PID_PODCASTS=$!

# Wait for all extractions to finish
log "Waiting for all extractions to complete..."
wait $PID_BOOKMARKS || true
wait $PID_PLAYLIST || true
wait $PID_PODCASTS || true
log "--- All extractions complete ---"

# ---------------------------------------------------------------------------
# Stage 4: Generate briefing (~5-10 min)
# ---------------------------------------------------------------------------
log "--- Stage 4: Generating briefing ---"
cd "$BRIEF_SIGNAL_DIR"
git checkout main
git pull origin main
git checkout -b "$BRANCH"

if node scripts/generate-briefing.js >> "$LOG_FILE" 2>&1; then
  log "Stage 4 complete: briefing generated."
else
  log "ERROR: Stage 4 failed (briefing generation). Cleaning up."
  git checkout main
  git branch -D "$BRANCH"
  exit 1
fi

# ---------------------------------------------------------------------------
# Stage 5: Fetch OG images, commit, push, open PR
# ---------------------------------------------------------------------------
log "--- Stage 5: Committing and opening PR ---"
npm run fetch-images >> "$LOG_FILE" 2>&1 || log "WARN: Some OG images failed to fetch."

git add content/briefings/
git commit -m "Add briefing: ${MONDAY_DATE}"
git push -u origin "$BRANCH"

PR_BODY="$(cat <<PREOF
## Weekly AI Market Briefing — ${MONDAY_DATE}

Auto-generated by the Brief Signal pipeline.

### Review checklist
- [ ] Read through briefing for accuracy
- [ ] Check source links work
- [ ] Verify OG images loaded
- [ ] Edit any wording/tone issues

### Pipeline stages
- **Bookmarks:** Extracted via twikit (if missing, cookies may have expired — see docs/cookie-refresh.md)
- **Playlist:** Extracted via parallel stage (check log for warnings)
- **Podcasts:** Extracted via parallel stage (check log for warnings)
- **Briefing:** Generated successfully

### After merging
Run \`npm run audio:pr\` to generate the audio script and open a PR.
Subscriber email is sent when the audio PR is merged.
PREOF
)"

gh pr create \
  --repo "$REPO" \
  --title "Briefing: Week of ${MONDAY_DATE}" \
  --body "$PR_BODY"

log "PR created. Returning to main."
git checkout main
log "=== Done ==="
